# Generated by Django 3.2.7 on 2021-09-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='default.jgp', null=True, upload_to='profile')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('withdraw_total', models.IntegerField(blank=True, default=0, null=True)),
                ('coin_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('uri', models.CharField(blank=True, default='7496311979225513185885856106769874', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
