# Generated by Django 3.2.7 on 2021-09-07 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uri',
            field=models.CharField(blank=True, default='c4fe5e12191e42d1b9cae11878a8cd', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transac_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('coin', models.CharField(max_length=100)),
                ('amount_in_coin', models.IntegerField(default=0)),
                ('amount_in_usd', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_usr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
