# Generated by Django 3.2.7 on 2021-09-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210907_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jgp', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uri',
            field=models.CharField(blank=True, default='633d55d133c840d0a8cfc3cad409be', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Buycoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('coin', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_in_coin', models.IntegerField(default=0)),
                ('amount_in_usd', models.IntegerField(default=0)),
                ('pop', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_usr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
