# Generated by Django 3.2.7 on 2021-09-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210908_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycoin',
            name='uri',
            field=models.CharField(blank=True, default='02c18d668889420d802f16df5a4fcc', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uri',
            field=models.CharField(blank=True, default='121e849e5be94de4ab0a71b5f8b0bd', max_length=50, null=True),
        ),
    ]
