# Generated by Django 3.2.7 on 2021-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210908_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycoin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uri',
            field=models.CharField(blank=True, default='bdc04b488b3a4aedb3c07667e4ad61', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buycoin',
            name='uri',
            field=models.CharField(blank=True, default='4cda7a643c1e4e96931bbbd59e5f09', max_length=50, null=True),
        ),
    ]
